baseURL = "https://xtiam57.vercel.app/"
languageCode = "es-ES"
title = "Christiam Mena Website"

enableEmoji = true
paginate = 10

[markup]
  [markup.highlight]
    guessSyntax = true
    noClasses = false
    tabWidth = 2

[markup.goldmark.renderer]
  unsafe = true
