baseURL = "https://christiam-mena.netlify.app/"
languageCode = "es-ES"
title = "Christiam Mena's Website"

enableEmoji = true
paginate = 10

[author]
  name = "Christiam Mena"

[params]
  image = "/images/logo-small.png"
  placeholderQuality = "100x q05"
  placeholderGaussian = 6

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/blog"
    weight = 1

  [[menu.main]]
    name = "Sobre mí"
    url = "/about"
    weight = 2

  [[menu.main]]
    name = "RSS"
    url = "/blog/index.xml"
    weight = 3

  [[menu.social]]
    name = "Github"
    url = "https://github.com/xtiam57"
    weight = 1

  [[menu.social]]
    name = "Twitter"
    url = "https://twitter.com/xtiam57"
    weight = 2

  [[menu.social]]
    name = "Instagram"
    url = "https://www.instagram.com/xtiam57/"
    weight = 3

[markup]
  [markup.highlight]
    guessSyntax = true
    noClasses = false
    tabWidth = 2

[markup.goldmark.renderer]
  unsafe = true

[related]
  threshold = 0
  includeNewer = true
  toLower = false

  [[related.indices]]
    name = "categories"
    weight = 100

  [[related.indices]]
    name = "tags"
    weight = 80

  [[related.indices]]
      name = "date"
      weight = 10
