baseURL = "https://learning-hugo.vercel.app/"
languageCode = "es-ES"
title = "My New Hugo Site!"

[markup]
  [markup.highlight]
    guessSyntax = true
    noClasses = false
    tabWidth = 2

[markup.goldmark.renderer]
unsafe= true
