baseURL = "https://xtiam57.vercel.app/"
languageCode = "es-ES"
title = "My New Hugo Site!"

enableEmoji = true
paginate = 2

[markup]
  [markup.highlight]
    guessSyntax = true
    noClasses = false
    tabWidth = 2

[markup.goldmark.renderer]
  unsafe = true
